name: Terraform AWS Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout the code
        uses: actions/checkout@v4
        
      - name: Setting up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2 

      - name: Setting up Terraform
        uses: hashicorp/setup-terraform@v1

      - name: Terraform Init
        run: terraform init
        working-directory: ./Terraform
      - name: Apply the infrastructure
        run: terraform apply  -var-file "dev.tfvars" -auto-approve
        working-directory: ./Terraform
