name: Terraform AWS Workflow

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'us-west-2'  
        run: |
          aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
          aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
          aws configure set region $AWS_DEFAULT_REGION

      - name:  Setting up terraform
        uses: hashicorp/terraform-github-actions/init@v0.4.0
      - name: Initialization
        run: terraform init
        working-directory: ./Terraform
      - name: Apply the infrastructure
        run: terraform apply -var user="${{ secrets.USER }}" -var privatekey="${{ secrets.PRIVATEKEY }}" -var ="${{ secrets.DOCKER_USERNAME }}" -var ="${{ secrets.DOCKER_PASSWORD }}" -var-file "dev.tfvars" -auto-approve
        working-directory: ./Terraform
